### ISSUE TITLE
Add proxy in SignerAPI spec and module

### ISSUE THREAD

**Issue by ltitanb** [Commit-Boost/commit-boost-client#19]
The proxy delegation needs to be documented in the `SignerAPI` spec and supported by the signer module. We should also evaluate whether we want to support non-proxy (i.e. consensus) signature requests, or allow only proxy ones for better safety

**Comment by Daniel-K-Ivanov** [comment]
I think that in the future CommitBoost should **NOT** allow direct (non-proxied) signing, meaning that it should not be possible for a module to request the validator keys to sign any payload.

The community will be able to more easily adopt CB if the modules do not have rights to the validator key, but rather modules can only issue and use proxy keys.

Enforcing the usage of proxy keys makes the statement that CB priorities security and this is something that we want to advocate and stick to.
