### ISSUE TITLE
Tidy up ssz types

### ISSUE THREAD

**Issue by ltitanb** [Commit-Boost/commit-boost-client#36]
We're currently using the `tree_hash` crate, and some hacky workaround since the crate doesn't support alloy yet, eg:

https://github.com/Commit-Boost/commit-boost-client/blob/cadefca902a8308b58b03976777d6a4a75ad8cd2/crates/pbs/src/types/execution_payload.rs#L85-L86

We should remove the workarounds once [this PR](https://github.com/sigp/tree_hash/pull/16) is merged

**Comment by David-Petrov** [comment]
The referred PR was merged today, so this issue is ready to pick up.
